"""Compute feasible torque sets from tendon networks.

Two modes:

1. Fixed-direction basis vectors (compute_feasible_set):
   The feasible set is the Minkowski sum of line segments
   [0, F_max_i * basis_i] for each tendon. With n tendons, the corners of
   that sum lie at the 2^n vertices generated by activating each tendon at
   either 0 or F_max. The feasible set is the convex hull of those.

2. Variable basis vector directions (sample_feasible_set):
   For network-routed cases (extensor hood, lumbrical) the effective moment
   arms depend on activation distribution. Caller provides a routing_fn that
   maps a tension vector to a torque vector, this samples the activation
   space and takes the convex hull of the result.
"""
from __future__ import annotations

import itertools
from dataclasses import dataclass, field
from typing import Callable, Optional, Sequence

import numpy as np
from scipy.spatial import ConvexHull
from scipy.spatial.qhull import QhullError

from tendon_network import Tendon, TendonNetwork


def _hull(points: np.ndarray) -> ConvexHull:
    """ConvexHull with a joggle fallback for coplanar / degenerate inputs.

    Degeneracy is common when two tendons have identical (or scalar-multiple)
    moment-arm vectors — e.g. DI2 and DI3 in a model that ignores radial/ulnar
    asymmetry. Joggle perturbs points slightly to break the degeneracy; volume
    and area then carry a small (<1%) joggle artifact, which is fine for the
    qualitative shape comparison this tool is built for.
    """
    try:
        return ConvexHull(points)
    except QhullError:
        return ConvexHull(points, qhull_options="QJ")


@dataclass
class FeasibleTorqueSet:
    network_name: str
    vertices: np.ndarray   # all sampled / corner points, shape (m, 3)
    hull: ConvexHull       # hull of those points
    network: Optional[TendonNetwork] = None  # source network, for basis vectors

    @property
    def hull_points(self) -> np.ndarray:
        return self.vertices[self.hull.vertices]

    @property
    def volume(self) -> float:
        return float(self.hull.volume)

    @property
    def surface_area(self) -> float:
        return float(self.hull.area)

    @property
    def octants_reached(self) -> set:
        """Sign-octants touched by the hull's extreme vertices.

        An octant is a tuple of signs like (+1, -1, +1). We ignore vertices
        that lie exactly on a coordinate plane (zero component) since they
        don't unambiguously belong to one octant.
        """
        signs = np.sign(self.hull_points).astype(int)
        return {tuple(s) for s in signs if 0 not in s}

    @property
    def num_octants_reached(self) -> int:
        return len(self.octants_reached)

    @property
    def principal_extents(self) -> np.ndarray:
        """Extent of the hull along its three principal axes (PCA), sorted
        descending. Tells you the polytope's true length, width, thickness
        regardless of how it sits in the MCP/PIP/DIP coordinate frame.
        """
        _, extents, _ = principal_axes(self.hull_points)
        return np.sort(extents)[::-1]

    @property
    def flatness(self) -> float:
        """Aspect ratio = thinnest principal extent / longest. 0 = perfectly
        flat, 1 = isotropic. Anything below ~0.05 reads visually flat from
        most viewing angles.
        """
        e = self.principal_extents
        if e[0] == 0:
            return 0.0
        return float(e[2] / e[0])

    def summary(self) -> str:
        e = self.principal_extents
        return (
            f"{self.network_name}: "
            f"vol={self.volume:.1f} N*mm^3, "
            f"area={self.surface_area:.1f} N*mm^2, "
            f"octants={self.num_octants_reached}/8, "
            f"extents={e[0]:.0f}x{e[1]:.0f}x{e[2]:.1f}, "
            f"flatness={self.flatness:.3f}"
        )


def principal_axes(vertices: np.ndarray):
    """PCA-based oriented bounding box of a point set.

    Returns:
        axes: (3, 3) — unit principal-direction vectors as rows
        extents: (3,) — span (max - min projection) along each axis
        center: (3,) — center of the oriented bounding box
    """
    pts = np.asarray(vertices, dtype=float)
    mean = pts.mean(axis=0)
    centered = pts - mean
    _, _, vt = np.linalg.svd(centered, full_matrices=False)
    axes = vt  # rows are principal-direction unit vectors
    proj = centered @ axes.T
    pmin = proj.min(axis=0)
    pmax = proj.max(axis=0)
    extents = pmax - pmin
    center = mean + ((pmin + pmax) / 2.0) @ axes
    return axes, extents, center


def obb_corners(vertices: np.ndarray) -> np.ndarray:
    """8 corners of the oriented bounding box, shape (8, 3)."""
    axes, extents, center = principal_axes(vertices)
    half = extents / 2.0
    signs = np.array(
        [[a, b, c] for a in (-1, 1) for b in (-1, 1) for c in (-1, 1)],
        dtype=float,
    )
    return center + (signs * half) @ axes


# Corner indices that form the 12 edges of a cube under the (-/+,-/+,-/+) ordering
# above: pairs of corners that differ in exactly one sign.
OBB_EDGES = (
    (0, 1), (0, 2), (0, 4),
    (1, 3), (1, 5),
    (2, 3), (2, 6),
    (3, 7),
    (4, 5), (4, 6),
    (5, 7),
    (6, 7),
)


def compute_feasible_set(network: TendonNetwork) -> FeasibleTorqueSet:
    """Polytope of all torques reachable with fixed-direction basis vectors."""
    n = len(network)
    if n < 3:
        raise ValueError(
            f"Need >= 3 tendons for a 3D feasible torque set; got {n}. "
            "For 2-tendon networks the polytope is planar; either add a "
            "third tendon or sample with sample_feasible_set."
        )

    max_torques = network.max_torques  # (n, 3)

    # 2^n activation patterns over (0 or F_max) for each tendon.
    activations = np.array(list(itertools.product([0.0, 1.0], repeat=n)))
    vertices = activations @ max_torques  # (2^n, 3)

    hull = _hull(vertices)
    return FeasibleTorqueSet(network.name, vertices, hull, network=network)


def sample_feasible_set(
    network: TendonNetwork,
    routing_fn: Callable[[np.ndarray], np.ndarray],
    n_samples_per_axis: int = 6,
) -> FeasibleTorqueSet:
    """Variable basis vector directions — sample activation space and hull it.

    routing_fn(forces) -> torque_vector
        Receives a length-n_tendons array of tendon tensions (in N) and
        returns the resulting (3,) joint-torque vector. Use this to encode
        extensor hood routing, lumbrical asymmetry, etc.

    n_samples_per_axis: grid resolution per tendon. Total samples grow as
        n_samples_per_axis ** n_tendons, so keep it small for many tendons.
    """
    n = len(network)
    if n < 1:
        raise ValueError("Network must have at least one tendon")

    grid = np.linspace(0.0, 1.0, n_samples_per_axis)
    max_forces = np.array([t.max_force for t in network.tendons])

    points = []
    for combo in itertools.product(grid, repeat=n):
        forces = np.array(combo) * max_forces
        tau = np.asarray(routing_fn(forces), dtype=float)
        if tau.shape != (3,):
            raise ValueError(
                f"routing_fn must return shape (3,), got {tau.shape}"
            )
        points.append(tau)

    vertices = np.array(points)
    hull = _hull(vertices)
    return FeasibleTorqueSet(
        f"{network.name} (sampled)", vertices, hull, network=network,
    )


def compare(*sets: FeasibleTorqueSet) -> dict:
    """Numeric side-by-side of multiple feasible torque sets."""
    return {
        s.network_name: {
            "volume": s.volume,
            "surface_area": s.surface_area,
            "octants_reached": s.num_octants_reached,
            "n_hull_vertices": len(s.hull.vertices),
        }
        for s in sets
    }
